<?php
defined('_JEXEC') or die('Restricted access');

class Sertifika_SorgulaModelSertifika_Sorgula extends JModel {
	
	function getBelgeDataByTcKimlikNo ($tckimlikno){
		$_db = JFactory::getOracleDBO ();
		$sertifika = array();
		
		$sql = " SELECT DISTINCT SERTIFIKA_BASVURU_ID, SERTIFIKA_DUZENLENME_TARIHI, SERTIFIKA_GECERLILIK_TARIHI,  SINAV_TARIHI, YETKILI, UNVAN, OGRENME_CIKTI,  SERTIFIKA_NO,  M_SINAV_ID, TC_KIMLIK, TO_CHAR(SERTIFIKA_BASVURU_TARIHI, 'dd.mm.yyyy') AS SER_TARIH, USER_ID, KURULUS_ADI, YETERLILIK_ID, YETERLILIK_KODU, YETERLILIK_ADI, SEVIYE_ID, OGRENCI_ADI, OGRENCI_SOYADI, OGRENCI_DOGUM_TARIHI, OGRENCI_DOGUM_YERI, OGRENCI_BABA_ADI,  
           YETERLILIK_ALT_BIRIM_ADI AS BIRIM_ADI, YETERLILIK_KODU AS BIRIM_KODU, YETERLILIK_ALT_BIRIM_NO AS BIRIM_NO ,  SERTIFIKA_DURUM_ID, SERTIFIKA_DURUM_ADI, REV_YETERLILIK_KODU, REVIZYON_NO, REV_YAYIN_TARIHI, REVIZYON_TARIHI, YENI_MI 
          FROM M_SERTIFIKA_BASVURU 
          			
					JOIN M_OGRENCI USING(TC_KIMLIK) 
					JOIN M_KURULUS USING(USER_ID) 
					JOIN M_YETERLILIK ON M_SERTIFIKA_BASVURU.YETERLILIK_ID = M_YETERLILIK.YETERLILIK_ID
          JOIN M_YETERLILIK_ALT_BIRIM ON (M_SERTIFIKA_BASVURU.BIRIM_ID = M_YETERLILIK_ALT_BIRIM.YETERLILIK_ALT_BIRIM_ID AND M_SERTIFIKA_BASVURU.YETERLILIK_ID = M_YETERLILIK_ALT_BIRIM.YETERLILIK_ID)
          JOIN PM_SERTIFIKA_DURUM USING(SERTIFIKA_DURUM_ID)
          WHERE YENI_MI = 0 AND TC_KIMLIK = ? 
          UNION
		   SELECT DISTINCT SERTIFIKA_BASVURU_ID, SERTIFIKA_DUZENLENME_TARIHI, SERTIFIKA_GECERLILIK_TARIHI,  SINAV_TARIHI, YETKILI, UNVAN, OGRENME_CIKTI,  SERTIFIKA_NO,  M_SINAV_ID, TC_KIMLIK, TO_CHAR(SERTIFIKA_BASVURU_TARIHI, 'dd.mm.yyyy') AS SER_TARIH, USER_ID, KURULUS_ADI, YETERLILIK_ID, YETERLILIK_KODU, YETERLILIK_ADI, SEVIYE_ID, OGRENCI_ADI, OGRENCI_SOYADI, OGRENCI_DOGUM_TARIHI, OGRENCI_DOGUM_YERI, OGRENCI_BABA_ADI, 
    		 BIRIM_ADI, BIRIM_KODU, BIRIM_NO,   SERTIFIKA_DURUM_ID, SERTIFIKA_DURUM_ADI, REV_YETERLILIK_KODU, REVIZYON_NO, REV_YAYIN_TARIHI, REVIZYON_TARIHI, YENI_MI 
		    FROM M_SERTIFIKA_BASVURU
					JOIN M_OGRENCI USING(TC_KIMLIK) 
					JOIN M_KURULUS USING(USER_ID) 
					JOIN M_YETERLILIK USING(YETERLILIK_ID)
          			JOIN M_BIRIM_OLCME_DEGERLENDIRME ON (M_SERTIFIKA_BASVURU.BIRIM_ID = M_BIRIM_OLCME_DEGERLENDIRME.BIRIM_ID AND M_SERTIFIKA_BASVURU.BIRIM_SINAV_ID = M_BIRIM_OLCME_DEGERLENDIRME.ID)
          			JOIN M_BIRIM ON M_SERTIFIKA_BASVURU.BIRIM_ID = M_BIRIM.BIRIM_ID
                JOIN PM_SERTIFIKA_DURUM USING(SERTIFIKA_DURUM_ID)
          WHERE YENI_MI = 1 AND TC_KIMLIK = ? ORDER BY SERTIFIKA_BASVURU_ID, TC_KIMLIK, BIRIM_KODU, BIRIM_NO";
		
		$params = array ($tckimlikno, $tckimlikno);
		$sertifika[0] = $_db->prep_exec($sql, $params);
		
		$sql2 = "SELECT * FROM M_BELGE_SORGU WHERE TCKIMLIKNO = ?";
		$sertifika[1] = $_db->prep_exec($sql2, array($tckimlikno));
		
		return $sertifika;
		//return $_db->prep_exec($sql, $params);
	}
	
	function getBelgeDataByKurulus ($kurulus){
		$_db = JFactory::getOracleDBO ();
		$sertifika = array();
	
		$sql = "SELECT DISTINCT SERTIFIKA_BASVURU_ID, SERTIFIKA_DUZENLENME_TARIHI, SERTIFIKA_GECERLILIK_TARIHI,  SINAV_TARIHI, YETKILI, UNVAN, OGRENME_CIKTI,  SERTIFIKA_NO,  M_SINAV_ID, TC_KIMLIK, TO_CHAR(SERTIFIKA_BASVURU_TARIHI, 'dd.mm.yyyy') AS SER_TARIH, USER_ID, KURULUS_ADI, YETERLILIK_ID, YETERLILIK_KODU, YETERLILIK_ADI, SEVIYE_ID, OGRENCI_ADI, OGRENCI_SOYADI, OGRENCI_DOGUM_TARIHI, OGRENCI_DOGUM_YERI, OGRENCI_BABA_ADI, 
				           YETERLILIK_ALT_BIRIM_ADI AS BIRIM_ADI, YETERLILIK_KODU AS BIRIM_KODU, YETERLILIK_ALT_BIRIM_NO AS BIRIM_NO ,  SERTIFIKA_DURUM_ID, SERTIFIKA_DURUM_ADI, REV_YETERLILIK_KODU, REVIZYON_NO, REV_YAYIN_TARIHI, REVIZYON_TARIHI, YENI_MI 
				          FROM M_SERTIFIKA_BASVURU
				          			 
									JOIN M_OGRENCI USING(TC_KIMLIK) 
									JOIN M_KURULUS USING(USER_ID) 
									JOIN M_YETERLILIK ON M_SERTIFIKA_BASVURU.YETERLILIK_ID = M_YETERLILIK.YETERLILIK_ID
				          JOIN M_YETERLILIK_ALT_BIRIM ON (M_SERTIFIKA_BASVURU.BIRIM_ID = M_YETERLILIK_ALT_BIRIM.YETERLILIK_ALT_BIRIM_ID AND M_SERTIFIKA_BASVURU.YETERLILIK_ID = M_YETERLILIK_ALT_BIRIM.YETERLILIK_ID)
				          JOIN PM_SERTIFIKA_DURUM USING(SERTIFIKA_DURUM_ID)
				          WHERE YENI_MI = 0 AND  USER_ID = ?
				UNION
				 SELECT DISTINCT SERTIFIKA_BASVURU_ID, SERTIFIKA_DUZENLENME_TARIHI, SERTIFIKA_GECERLILIK_TARIHI,  SINAV_TARIHI, YETKILI, UNVAN, OGRENME_CIKTI,  SERTIFIKA_NO,  M_SINAV_ID, TC_KIMLIK, TO_CHAR(SERTIFIKA_BASVURU_TARIHI, 'dd.mm.yyyy') AS SER_TARIH, USER_ID, KURULUS_ADI, YETERLILIK_ID, YETERLILIK_KODU, YETERLILIK_ADI, SEVIYE_ID, OGRENCI_ADI, OGRENCI_SOYADI, OGRENCI_DOGUM_TARIHI, OGRENCI_DOGUM_YERI, OGRENCI_BABA_ADI, 
		    		 BIRIM_ADI, BIRIM_KODU, BIRIM_NO,   SERTIFIKA_DURUM_ID, SERTIFIKA_DURUM_ADI, REV_YETERLILIK_KODU, REVIZYON_NO, REV_YAYIN_TARIHI, REVIZYON_TARIHI, YENI_MI 
				    FROM M_SERTIFIKA_BASVURU
							JOIN M_OGRENCI USING(TC_KIMLIK) 
							JOIN M_KURULUS USING(USER_ID) 
							JOIN M_YETERLILIK USING(YETERLILIK_ID)
			          	JOIN M_BIRIM_OLCME_DEGERLENDIRME ON (M_SERTIFIKA_BASVURU.BIRIM_ID = M_BIRIM_OLCME_DEGERLENDIRME.BIRIM_ID AND M_SERTIFIKA_BASVURU.BIRIM_SINAV_ID = M_BIRIM_OLCME_DEGERLENDIRME.ID)
	          			JOIN M_BIRIM ON M_SERTIFIKA_BASVURU.BIRIM_ID = M_BIRIM.BIRIM_ID
                		JOIN PM_SERTIFIKA_DURUM USING(SERTIFIKA_DURUM_ID)
				          WHERE YENI_MI = 1 AND USER_ID = ? ORDER BY SERTIFIKA_BASVURU_ID, TC_KIMLIK, BIRIM_KODU, BIRIM_NO";
	
		$params = array ($kurulus, $kurulus);
		$sertifika[0] = $_db->prep_exec($sql, $params);
		
		$kursql = "SELECT KURULUS_ADI FROM M_KURULUS WHERE USER_ID = ?";
		$belgekur = $_db->prep_exec($kursql, array($kurulus)); 
		
		$sql2 = "SELECT * FROM M_BELGE_SORGU WHERE UCASE(BELGELENDIRME_KURULUSU) = UCASE(?)";
		$sertifika[1] = $_db->prep_exec($sql2, array($belgekur[0]["KURULUS_ADI"]));
		
		return $sertifika;
		//return $_db->prep_exec($sql, $params);
	}
	
	function getBelgeDataByTarih ($tarih){
		$_db = JFactory::getOracleDBO ();
		$sertifika = array();
	
		$sql = "  SELECT DISTINCT SERTIFIKA_BASVURU_ID, SERTIFIKA_DUZENLENME_TARIHI, SERTIFIKA_GECERLILIK_TARIHI,  SINAV_TARIHI, YETKILI, UNVAN, OGRENME_CIKTI,  SERTIFIKA_NO,  M_SINAV_ID, TC_KIMLIK, TO_CHAR(SERTIFIKA_BASVURU_TARIHI, 'dd.mm.yyyy') AS SER_TARIH, USER_ID, KURULUS_ADI, YETERLILIK_ID, YETERLILIK_KODU, YETERLILIK_ADI, SEVIYE_ID, OGRENCI_ADI, OGRENCI_SOYADI, OGRENCI_DOGUM_TARIHI, OGRENCI_DOGUM_YERI, OGRENCI_BABA_ADI, 
				           YETERLILIK_ALT_BIRIM_ADI AS BIRIM_ADI, YETERLILIK_KODU AS BIRIM_KODU, YETERLILIK_ALT_BIRIM_NO AS BIRIM_NO ,  SERTIFIKA_DURUM_ID, SERTIFIKA_DURUM_ADI, REV_YETERLILIK_KODU, REVIZYON_NO, REV_YAYIN_TARIHI, REVIZYON_TARIHI, YENI_MI 
				          FROM M_SERTIFIKA_BASVURU 
				          			
									JOIN M_OGRENCI USING(TC_KIMLIK) 
									JOIN M_KURULUS USING(USER_ID) 
									JOIN M_YETERLILIK ON M_SERTIFIKA_BASVURU.YETERLILIK_ID = M_YETERLILIK.YETERLILIK_ID
				          JOIN M_YETERLILIK_ALT_BIRIM ON (M_SERTIFIKA_BASVURU.BIRIM_ID = M_YETERLILIK_ALT_BIRIM.YETERLILIK_ALT_BIRIM_ID AND M_SERTIFIKA_BASVURU.YETERLILIK_ID = M_YETERLILIK_ALT_BIRIM.YETERLILIK_ID)
				          JOIN PM_SERTIFIKA_DURUM USING(SERTIFIKA_DURUM_ID)
				          WHERE TO_CHAR(SERTIFIKA_BASVURU_TARIHI, 'dd.mm.yyyy') = ? AND YENI_MI = 0 
				UNION
				 SELECT DISTINCT SERTIFIKA_BASVURU_ID, SERTIFIKA_DUZENLENME_TARIHI, SERTIFIKA_GECERLILIK_TARIHI,  SINAV_TARIHI, YETKILI, UNVAN, OGRENME_CIKTI,  SERTIFIKA_NO,  M_SINAV_ID, TC_KIMLIK, TO_CHAR(SERTIFIKA_BASVURU_TARIHI, 'dd.mm.yyyy') AS SER_TARIH, USER_ID, KURULUS_ADI, YETERLILIK_ID, YETERLILIK_KODU, YETERLILIK_ADI, SEVIYE_ID, OGRENCI_ADI, OGRENCI_SOYADI, OGRENCI_DOGUM_TARIHI, OGRENCI_DOGUM_YERI, OGRENCI_BABA_ADI, 
    		 BIRIM_ADI, BIRIM_KODU, BIRIM_NO,   SERTIFIKA_DURUM_ID, SERTIFIKA_DURUM_ADI, REV_YETERLILIK_KODU, REVIZYON_NO, REV_YAYIN_TARIHI, REVIZYON_TARIHI, YENI_MI 
		    FROM M_SERTIFIKA_BASVURU
					JOIN M_OGRENCI USING(TC_KIMLIK) 
					JOIN M_KURULUS USING(USER_ID) 
					JOIN M_YETERLILIK USING(YETERLILIK_ID)
          JOIN M_BIRIM_OLCME_DEGERLENDIRME ON (M_SERTIFIKA_BASVURU.BIRIM_ID = M_BIRIM_OLCME_DEGERLENDIRME.BIRIM_ID AND M_SERTIFIKA_BASVURU.BIRIM_SINAV_ID = M_BIRIM_OLCME_DEGERLENDIRME.ID)
          			JOIN M_BIRIM ON M_SERTIFIKA_BASVURU.BIRIM_ID = M_BIRIM.BIRIM_ID
                JOIN PM_SERTIFIKA_DURUM USING(SERTIFIKA_DURUM_ID)
				          WHERE TO_CHAR(SERTIFIKA_BASVURU_TARIHI, 'dd.mm.yyyy') = ? AND YENI_MI = 1 ORDER BY SERTIFIKA_BASVURU_ID, TC_KIMLIK, BIRIM_KODU, BIRIM_NO ";
	
		$params = array ($tarih, $tarih);
		$sertifika[0] =  $_db->prep_exec($sql, $params);
		return $sertifika;
		//return $_db->prep_exec($sql, $params);
	}
	
	function getBelgeDataByYeterlilik ($yetId){
		$_db = JFactory::getOracleDBO ();
		$sertifika = array();
	
		$sql = "  SELECT DISTINCT SERTIFIKA_BASVURU_ID, SERTIFIKA_DUZENLENME_TARIHI, SERTIFIKA_GECERLILIK_TARIHI,  SINAV_TARIHI, YETKILI, UNVAN, OGRENME_CIKTI,  SERTIFIKA_NO,  M_SINAV_ID, TC_KIMLIK, TO_CHAR(SERTIFIKA_BASVURU_TARIHI, 'dd.mm.yyyy') AS SER_TARIH, USER_ID, KURULUS_ADI, YETERLILIK_ID, YETERLILIK_KODU, YETERLILIK_ADI, SEVIYE_ID, OGRENCI_ADI, OGRENCI_SOYADI, OGRENCI_DOGUM_TARIHI, OGRENCI_DOGUM_YERI, OGRENCI_BABA_ADI, 
				           YETERLILIK_ALT_BIRIM_ADI AS BIRIM_ADI, YETERLILIK_KODU AS BIRIM_KODU, YETERLILIK_ALT_BIRIM_NO AS BIRIM_NO ,  SERTIFIKA_DURUM_ID, SERTIFIKA_DURUM_ADI, REV_YETERLILIK_KODU, REVIZYON_NO, REV_YAYIN_TARIHI, REVIZYON_TARIHI, YENI_MI 
				          FROM M_SERTIFIKA_BASVURU 
				          
									JOIN M_OGRENCI USING(TC_KIMLIK) 
									JOIN M_KURULUS USING(USER_ID) 
									JOIN M_YETERLILIK ON M_SERTIFIKA_BASVURU.YETERLILIK_ID = M_YETERLILIK.YETERLILIK_ID
				          JOIN M_YETERLILIK_ALT_BIRIM ON (M_SERTIFIKA_BASVURU.BIRIM_ID = M_YETERLILIK_ALT_BIRIM.YETERLILIK_ALT_BIRIM_ID AND M_SERTIFIKA_BASVURU.YETERLILIK_ID = M_YETERLILIK_ALT_BIRIM.YETERLILIK_ID)
				          JOIN PM_SERTIFIKA_DURUM USING(SERTIFIKA_DURUM_ID)
				          WHERE YENI_MI = 0 AND YETERLILIK_ID = ? 
				UNION
				 SELECT DISTINCT SERTIFIKA_BASVURU_ID, SERTIFIKA_DUZENLENME_TARIHI, SERTIFIKA_GECERLILIK_TARIHI,  SINAV_TARIHI, YETKILI, UNVAN, OGRENME_CIKTI,  SERTIFIKA_NO,  M_SINAV_ID, TC_KIMLIK, TO_CHAR(SERTIFIKA_BASVURU_TARIHI, 'dd.mm.yyyy') AS SER_TARIH, USER_ID, KURULUS_ADI, YETERLILIK_ID, YETERLILIK_KODU, YETERLILIK_ADI, SEVIYE_ID, OGRENCI_ADI, OGRENCI_SOYADI, OGRENCI_DOGUM_TARIHI, OGRENCI_DOGUM_YERI, OGRENCI_BABA_ADI, 
    		 BIRIM_ADI, BIRIM_KODU, BIRIM_NO,   SERTIFIKA_DURUM_ID, SERTIFIKA_DURUM_ADI, REV_YETERLILIK_KODU, REVIZYON_NO, REV_YAYIN_TARIHI, REVIZYON_TARIHI, YENI_MI 
		    FROM M_SERTIFIKA_BASVURU
					JOIN M_OGRENCI USING(TC_KIMLIK) 
					JOIN M_KURULUS USING(USER_ID) 
					JOIN M_YETERLILIK USING(YETERLILIK_ID)
          JOIN M_BIRIM_OLCME_DEGERLENDIRME ON (M_SERTIFIKA_BASVURU.BIRIM_ID = M_BIRIM_OLCME_DEGERLENDIRME.BIRIM_ID AND M_SERTIFIKA_BASVURU.BIRIM_SINAV_ID = M_BIRIM_OLCME_DEGERLENDIRME.ID)
          			JOIN M_BIRIM ON M_SERTIFIKA_BASVURU.BIRIM_ID = M_BIRIM.BIRIM_ID
                JOIN PM_SERTIFIKA_DURUM USING(SERTIFIKA_DURUM_ID)
				          WHERE YENI_MI = 1 AND YETERLILIK_ID = ? ORDER BY SERTIFIKA_BASVURU_ID, TC_KIMLIK, BIRIM_KODU, BIRIM_NO";
	
		$params = array ($yetId, $yetId);
		$sertifika[0] = $_db->prep_exec($sql, $params);
		
		$yetsql = "SELECT YETERLILIK_ADI FROM M_YETERLILIK WHERE YETERLILIK_ID = ?";
		$yetad = $_db->prep_exec($yetsql, array($yetId));
		
		$sql2 = "SELECT * FROM M_BELGE_SORGU WHERE UCASE(YETERLILIK_ADI) = UCASE(?)";
		$sertifika[1] = $_db->prep_exec($sql2, array($yetad[0]["YETERLILIK_ADI"]));
		return $sertifika;
		//return $_db->prep_exec($sql, $params);
	}
	
	function getBelgeDataByHepsi($kimlik_no, $kurulus, $tarih, $yeterlilik){
		$_db = JFactory::getOracleDBO ();
		$sertifika = array();
	
		$sql = "  SELECT DISTINCT SERTIFIKA_BASVURU_ID, SERTIFIKA_DUZENLENME_TARIHI, SERTIFIKA_GECERLILIK_TARIHI,  SINAV_TARIHI, YETKILI, UNVAN, OGRENME_CIKTI,  SERTIFIKA_NO,  M_SINAV_ID, TC_KIMLIK, TO_CHAR(SERTIFIKA_BASVURU_TARIHI, 'dd.mm.yyyy') AS SER_TARIH, USER_ID, KURULUS_ADI, YETERLILIK_ID, YETERLILIK_KODU, YETERLILIK_ADI, SEVIYE_ID, OGRENCI_ADI, OGRENCI_SOYADI, OGRENCI_DOGUM_TARIHI, OGRENCI_DOGUM_YERI, OGRENCI_BABA_ADI, 
				           YETERLILIK_ALT_BIRIM_ADI AS BIRIM_ADI, YETERLILIK_KODU AS BIRIM_KODU, YETERLILIK_ALT_BIRIM_NO AS BIRIM_NO ,  SERTIFIKA_DURUM_ID, SERTIFIKA_DURUM_ADI, REV_YETERLILIK_KODU, REVIZYON_NO, REV_YAYIN_TARIHI, REVIZYON_TARIHI, YENI_MI 
				          FROM M_SERTIFIKA_BASVURU 
				          
									JOIN M_OGRENCI USING(TC_KIMLIK) 
									JOIN M_KURULUS USING(USER_ID) 
									JOIN M_YETERLILIK ON M_SERTIFIKA_BASVURU.YETERLILIK_ID = M_YETERLILIK.YETERLILIK_ID
				          JOIN M_YETERLILIK_ALT_BIRIM ON (M_SERTIFIKA_BASVURU.BIRIM_ID = M_YETERLILIK_ALT_BIRIM.YETERLILIK_ALT_BIRIM_ID AND M_SERTIFIKA_BASVURU.YETERLILIK_ID = M_YETERLILIK_ALT_BIRIM.YETERLILIK_ID)
				          JOIN PM_SERTIFIKA_DURUM USING(SERTIFIKA_DURUM_ID)
				          WHERE YENI_MI = 0 AND TC_KIMLIK = ? AND USER_ID = ? AND TO_CHAR(SERTIFIKA_BASVURU_TARIHI, 'dd.mm.yyyy') = ? AND YETERLILIK_ID = ? 
				UNION
				 SELECT DISTINCT SERTIFIKA_BASVURU_ID, SERTIFIKA_DUZENLENME_TARIHI, SERTIFIKA_GECERLILIK_TARIHI,  SINAV_TARIHI, YETKILI, UNVAN, OGRENME_CIKTI,  SERTIFIKA_NO,  M_SINAV_ID, TC_KIMLIK, TO_CHAR(SERTIFIKA_BASVURU_TARIHI, 'dd.mm.yyyy') AS SER_TARIH, USER_ID, KURULUS_ADI, YETERLILIK_ID, YETERLILIK_KODU, YETERLILIK_ADI, SEVIYE_ID, OGRENCI_ADI, OGRENCI_SOYADI, OGRENCI_DOGUM_TARIHI, OGRENCI_DOGUM_YERI, OGRENCI_BABA_ADI, 
    		 BIRIM_ADI, BIRIM_KODU, BIRIM_NO,   SERTIFIKA_DURUM_ID, SERTIFIKA_DURUM_ADI, REV_YETERLILIK_KODU, REVIZYON_NO, REV_YAYIN_TARIHI, REVIZYON_TARIHI, YENI_MI 
		    FROM M_SERTIFIKA_BASVURU
					JOIN M_OGRENCI USING(TC_KIMLIK) 
					JOIN M_KURULUS USING(USER_ID) 
					JOIN M_YETERLILIK USING(YETERLILIK_ID)
          JOIN M_BIRIM_OLCME_DEGERLENDIRME ON (M_SERTIFIKA_BASVURU.BIRIM_ID = M_BIRIM_OLCME_DEGERLENDIRME.BIRIM_ID AND M_SERTIFIKA_BASVURU.BIRIM_SINAV_ID = M_BIRIM_OLCME_DEGERLENDIRME.ID)
          			JOIN M_BIRIM ON M_SERTIFIKA_BASVURU.BIRIM_ID = M_BIRIM.BIRIM_ID
                JOIN PM_SERTIFIKA_DURUM USING(SERTIFIKA_DURUM_ID)
				          WHERE YENI_MI = 1 AND TC_KIMLIK = ? AND USER_ID = ? AND TO_CHAR(SERTIFIKA_BASVURU_TARIHI, 'dd.mm.yyyy') = ? AND YETERLILIK_ID = ? ORDER BY SERTIFIKA_BASVURU_ID, TC_KIMLIK, BIRIM_KODU, BIRIM_NO";
	
		$params = array($kimlik_no, $kurulus, $tarih, $yeterlilik, $kimlik_no, $kurulus, $tarih, $yeterlilik);
		$sertifika[0] = $_db->prep_exec($sql, $params);
		return $sertifika;
		//return $_db->prep_exec($sql, $params);
	}
	
	function getBelgeDataByTCKURTAR($kimlik_no, $kurulus, $tarih){
		$_db = JFactory::getOracleDBO ();
		$sertifika = array();
		
		$sql = "  SELECT DISTINCT SERTIFIKA_BASVURU_ID, SERTIFIKA_DUZENLENME_TARIHI, SERTIFIKA_GECERLILIK_TARIHI,  SINAV_TARIHI, YETKILI, UNVAN, OGRENME_CIKTI,  SERTIFIKA_NO,  M_SINAV_ID, TC_KIMLIK, TO_CHAR(SERTIFIKA_BASVURU_TARIHI, 'dd.mm.yyyy') AS SER_TARIH, USER_ID, KURULUS_ADI, YETERLILIK_ID, YETERLILIK_KODU, YETERLILIK_ADI, SEVIYE_ID, OGRENCI_ADI, OGRENCI_SOYADI, OGRENCI_DOGUM_TARIHI, OGRENCI_DOGUM_YERI, OGRENCI_BABA_ADI, 
				           YETERLILIK_ALT_BIRIM_ADI AS BIRIM_ADI, YETERLILIK_KODU AS BIRIM_KODU, YETERLILIK_ALT_BIRIM_NO AS BIRIM_NO ,  SERTIFIKA_DURUM_ID, SERTIFIKA_DURUM_ADI, REV_YETERLILIK_KODU, REVIZYON_NO, REV_YAYIN_TARIHI, REVIZYON_TARIHI, YENI_MI 
				          FROM M_SERTIFIKA_BASVURU 
				          
									JOIN M_OGRENCI USING(TC_KIMLIK) 
									JOIN M_KURULUS USING(USER_ID) 
									JOIN M_YETERLILIK ON M_SERTIFIKA_BASVURU.YETERLILIK_ID = M_YETERLILIK.YETERLILIK_ID
				          JOIN M_YETERLILIK_ALT_BIRIM ON (M_SERTIFIKA_BASVURU.BIRIM_ID = M_YETERLILIK_ALT_BIRIM.YETERLILIK_ALT_BIRIM_ID AND M_SERTIFIKA_BASVURU.YETERLILIK_ID = M_YETERLILIK_ALT_BIRIM.YETERLILIK_ID)
				          JOIN PM_SERTIFIKA_DURUM USING(SERTIFIKA_DURUM_ID)
				          WHERE YENI_MI = 0 AND TC_KIMLIK = ? AND TO_CHAR(SERTIFIKA_BASVURU_TARIHI, 'dd.mm.yyyy') = ? AND USER_ID = ? 
				UNION
				 SELECT DISTINCT SERTIFIKA_BASVURU_ID, SERTIFIKA_DUZENLENME_TARIHI, SERTIFIKA_GECERLILIK_TARIHI,  SINAV_TARIHI, YETKILI, UNVAN, OGRENME_CIKTI,  SERTIFIKA_NO,  M_SINAV_ID, TC_KIMLIK, TO_CHAR(SERTIFIKA_BASVURU_TARIHI, 'dd.mm.yyyy') AS SER_TARIH, USER_ID, KURULUS_ADI, YETERLILIK_ID, YETERLILIK_KODU, YETERLILIK_ADI, SEVIYE_ID, OGRENCI_ADI, OGRENCI_SOYADI, OGRENCI_DOGUM_TARIHI, OGRENCI_DOGUM_YERI, OGRENCI_BABA_ADI, 
    		 BIRIM_ADI, BIRIM_KODU, BIRIM_NO,   SERTIFIKA_DURUM_ID, SERTIFIKA_DURUM_ADI, REV_YETERLILIK_KODU, REVIZYON_NO, REV_YAYIN_TARIHI, REVIZYON_TARIHI, YENI_MI 
		    FROM M_SERTIFIKA_BASVURU
					JOIN M_OGRENCI USING(TC_KIMLIK) 
					JOIN M_KURULUS USING(USER_ID) 
					JOIN M_YETERLILIK USING(YETERLILIK_ID)
          JOIN M_BIRIM_OLCME_DEGERLENDIRME ON (M_SERTIFIKA_BASVURU.BIRIM_ID = M_BIRIM_OLCME_DEGERLENDIRME.BIRIM_ID AND M_SERTIFIKA_BASVURU.BIRIM_SINAV_ID = M_BIRIM_OLCME_DEGERLENDIRME.ID)
          			JOIN M_BIRIM ON M_SERTIFIKA_BASVURU.BIRIM_ID = M_BIRIM.BIRIM_ID
                JOIN PM_SERTIFIKA_DURUM USING(SERTIFIKA_DURUM_ID)
				          WHERE YENI_MI = 1 AND TC_KIMLIK = ? AND TO_CHAR(SERTIFIKA_BASVURU_TARIHI, 'dd.mm.yyyy') = ? AND USER_ID = ? ORDER BY SERTIFIKA_BASVURU_ID, TC_KIMLIK, BIRIM_KODU, BIRIM_NO";
		
		$params = array($kimlik_no, $tarih, $kurulus, $kimlik_no, $tarih, $kurulus);
		$sertifika[0] = $_db->prep_exec($sql, $params);
		return $sertifika;
		//return $_db->prep_exec($sql, $params);
	}
	
	function getBelgeDataByTCKURYET($kimlik_no, $kurulus, $yeterlilik){
		$_db = JFactory::getOracleDBO ();
		$sertifika = array();
		
		$sql = "  SELECT DISTINCT SERTIFIKA_BASVURU_ID, SERTIFIKA_DUZENLENME_TARIHI, SERTIFIKA_GECERLILIK_TARIHI,  SINAV_TARIHI, YETKILI, UNVAN, OGRENME_CIKTI,  SERTIFIKA_NO,  M_SINAV_ID, TC_KIMLIK, TO_CHAR(SERTIFIKA_BASVURU_TARIHI, 'dd.mm.yyyy') AS SER_TARIH, USER_ID, KURULUS_ADI, YETERLILIK_ID, YETERLILIK_KODU, YETERLILIK_ADI, SEVIYE_ID, OGRENCI_ADI, OGRENCI_SOYADI, OGRENCI_DOGUM_TARIHI, OGRENCI_DOGUM_YERI, OGRENCI_BABA_ADI, 
				           YETERLILIK_ALT_BIRIM_ADI AS BIRIM_ADI, YETERLILIK_KODU AS BIRIM_KODU, YETERLILIK_ALT_BIRIM_NO AS BIRIM_NO ,  SERTIFIKA_DURUM_ID, SERTIFIKA_DURUM_ADI, REV_YETERLILIK_KODU, REVIZYON_NO, REV_YAYIN_TARIHI, REVIZYON_TARIHI, YENI_MI 
				          FROM M_SERTIFIKA_BASVURU 
				          
									JOIN M_OGRENCI USING(TC_KIMLIK) 
									JOIN M_KURULUS USING(USER_ID) 
									JOIN M_YETERLILIK ON M_SERTIFIKA_BASVURU.YETERLILIK_ID = M_YETERLILIK.YETERLILIK_ID
				          JOIN M_YETERLILIK_ALT_BIRIM ON (M_SERTIFIKA_BASVURU.BIRIM_ID = M_YETERLILIK_ALT_BIRIM.YETERLILIK_ALT_BIRIM_ID AND M_SERTIFIKA_BASVURU.YETERLILIK_ID = M_YETERLILIK_ALT_BIRIM.YETERLILIK_ID)
				          JOIN PM_SERTIFIKA_DURUM USING(SERTIFIKA_DURUM_ID)
				          WHERE YENI_MI = 0 AND TC_KIMLIK = ? AND USER_ID = ? AND YETERLILIK_ID = ? 
				UNION
				 SELECT DISTINCT SERTIFIKA_BASVURU_ID, SERTIFIKA_DUZENLENME_TARIHI, SERTIFIKA_GECERLILIK_TARIHI,  SINAV_TARIHI, YETKILI, UNVAN, OGRENME_CIKTI,  SERTIFIKA_NO,  M_SINAV_ID, TC_KIMLIK, TO_CHAR(SERTIFIKA_BASVURU_TARIHI, 'dd.mm.yyyy') AS SER_TARIH, USER_ID, KURULUS_ADI, YETERLILIK_ID, YETERLILIK_KODU, YETERLILIK_ADI, SEVIYE_ID, OGRENCI_ADI, OGRENCI_SOYADI, OGRENCI_DOGUM_TARIHI, OGRENCI_DOGUM_YERI, OGRENCI_BABA_ADI, 
    		 BIRIM_ADI, BIRIM_KODU, BIRIM_NO,   SERTIFIKA_DURUM_ID, SERTIFIKA_DURUM_ADI, REV_YETERLILIK_KODU, REVIZYON_NO, REV_YAYIN_TARIHI, REVIZYON_TARIHI, YENI_MI 
		    FROM M_SERTIFIKA_BASVURU
					JOIN M_OGRENCI USING(TC_KIMLIK) 
					JOIN M_KURULUS USING(USER_ID) 
					JOIN M_YETERLILIK USING(YETERLILIK_ID)
          JOIN M_BIRIM_OLCME_DEGERLENDIRME ON (M_SERTIFIKA_BASVURU.BIRIM_ID = M_BIRIM_OLCME_DEGERLENDIRME.BIRIM_ID AND M_SERTIFIKA_BASVURU.BIRIM_SINAV_ID = M_BIRIM_OLCME_DEGERLENDIRME.ID)
          			JOIN M_BIRIM ON M_SERTIFIKA_BASVURU.BIRIM_ID = M_BIRIM.BIRIM_ID
                JOIN PM_SERTIFIKA_DURUM USING(SERTIFIKA_DURUM_ID)
				          WHERE YENI_MI = 1 AND TC_KIMLIK = ? AND USER_ID = ? AND YETERLILIK_ID = ? ORDER BY SERTIFIKA_BASVURU_ID, TC_KIMLIK, BIRIM_KODU, BIRIM_NO";
		
		$params = array($kimlik_no, $kurulus, $yeterlilik, $kimlik_no, $kurulus, $yeterlilik);
		$sertifika[0] =  $_db->prep_exec($sql, $params);
		
		$kursql = "SELECT KURULUS_ADI FROM M_KURULUS WHERE USER_ID = ?";
		$belgekur = $_db->prep_exec($kursql, array($kurulus));
		
		$yetsql = "SELECT YETERLILIK_ADI FROM M_YETERLILIK WHERE YETERLILIK_ID = ?";
		$yetad = $_db->prep_exec($yetsql, array($yeterlilik));
		
		$sql2 = "SELECT * FROM M_BELGE_SORGU WHERE TCKIMLIKNO = ? AND UCASE(YETERLILIK_ADI) = UCASE(?) AND UCASE(BELGELENDIRME_KURULUSU) = UCASE(?)";
		$sertifika[1] = $_db->prep_exec($sql2, array($kimlik_no, $yetad[0]["YETERLILIK_ADI"], $belgekur[0]["KURULUS_ADI"]));
		
		return $sertifika;
		//return $_db->prep_exec($sql, $params);
	}
	
	function getBelgeDataByTCTARYET($kimlik_no, $tarih, $yeterlilik){
		$_db = JFactory::getOracleDBO ();
		$sertifika = array();
		
		$sql = "  SELECT DISTINCT SERTIFIKA_BASVURU_ID, SERTIFIKA_DUZENLENME_TARIHI, SERTIFIKA_GECERLILIK_TARIHI,  SINAV_TARIHI, YETKILI, UNVAN, OGRENME_CIKTI,  SERTIFIKA_NO,  M_SINAV_ID, TC_KIMLIK, TO_CHAR(SERTIFIKA_BASVURU_TARIHI, 'dd.mm.yyyy') AS SER_TARIH, USER_ID, KURULUS_ADI, YETERLILIK_ID, YETERLILIK_KODU, YETERLILIK_ADI, SEVIYE_ID, OGRENCI_ADI, OGRENCI_SOYADI, OGRENCI_DOGUM_TARIHI, OGRENCI_DOGUM_YERI, OGRENCI_BABA_ADI, 
				           YETERLILIK_ALT_BIRIM_ADI AS BIRIM_ADI, YETERLILIK_KODU AS BIRIM_KODU, YETERLILIK_ALT_BIRIM_NO AS BIRIM_NO ,  SERTIFIKA_DURUM_ID, SERTIFIKA_DURUM_ADI, REV_YETERLILIK_KODU, REVIZYON_NO, REV_YAYIN_TARIHI, REVIZYON_TARIHI, YENI_MI 
				          FROM M_SERTIFIKA_BASVURU 
				          
									JOIN M_OGRENCI USING(TC_KIMLIK) 
									JOIN M_KURULUS USING(USER_ID) 
									JOIN M_YETERLILIK ON M_SERTIFIKA_BASVURU.YETERLILIK_ID = M_YETERLILIK.YETERLILIK_ID
				          JOIN M_YETERLILIK_ALT_BIRIM ON (M_SERTIFIKA_BASVURU.BIRIM_ID = M_YETERLILIK_ALT_BIRIM.YETERLILIK_ALT_BIRIM_ID AND M_SERTIFIKA_BASVURU.YETERLILIK_ID = M_YETERLILIK_ALT_BIRIM.YETERLILIK_ID)
				          JOIN PM_SERTIFIKA_DURUM USING(SERTIFIKA_DURUM_ID)
				          WHERE YENI_MI = 0 AND TC_KIMLIK = ? AND TO_CHAR(SERTIFIKA_BASVURU_TARIHI, 'dd.mm.yyyy') = ? AND YETERLILIK_ID = ? 
				UNION
				 SELECT DISTINCT SERTIFIKA_BASVURU_ID, SERTIFIKA_DUZENLENME_TARIHI, SERTIFIKA_GECERLILIK_TARIHI,  SINAV_TARIHI, YETKILI, UNVAN, OGRENME_CIKTI,  SERTIFIKA_NO,  M_SINAV_ID, TC_KIMLIK, TO_CHAR(SERTIFIKA_BASVURU_TARIHI, 'dd.mm.yyyy') AS SER_TARIH, USER_ID, KURULUS_ADI, YETERLILIK_ID, YETERLILIK_KODU, YETERLILIK_ADI, SEVIYE_ID, OGRENCI_ADI, OGRENCI_SOYADI, OGRENCI_DOGUM_TARIHI, OGRENCI_DOGUM_YERI, OGRENCI_BABA_ADI, 
    		 BIRIM_ADI, BIRIM_KODU, BIRIM_NO,   SERTIFIKA_DURUM_ID, SERTIFIKA_DURUM_ADI, REV_YETERLILIK_KODU, REVIZYON_NO, REV_YAYIN_TARIHI, REVIZYON_TARIHI, YENI_MI 
		    FROM M_SERTIFIKA_BASVURU
					JOIN M_OGRENCI USING(TC_KIMLIK) 
					JOIN M_KURULUS USING(USER_ID) 
					JOIN M_YETERLILIK USING(YETERLILIK_ID)
          JOIN M_BIRIM_OLCME_DEGERLENDIRME ON (M_SERTIFIKA_BASVURU.BIRIM_ID = M_BIRIM_OLCME_DEGERLENDIRME.BIRIM_ID AND M_SERTIFIKA_BASVURU.BIRIM_SINAV_ID = M_BIRIM_OLCME_DEGERLENDIRME.ID)
          			JOIN M_BIRIM ON M_SERTIFIKA_BASVURU.BIRIM_ID = M_BIRIM.BIRIM_ID
                JOIN PM_SERTIFIKA_DURUM USING(SERTIFIKA_DURUM_ID)
				          WHERE YENI_MI = 1 AND TC_KIMLIK = ? AND TO_CHAR(SERTIFIKA_BASVURU_TARIHI, 'dd.mm.yyyy') = ? AND YETERLILIK_ID = ? ORDER BY SERTIFIKA_BASVURU_ID, TC_KIMLIK, BIRIM_KODU, BIRIM_NO";
		
		$params = array($kimlik_no, $tarih, $yeterlilik, $kimlik_no, $tarih, $yeterlilik);
		$sertifika[0] =  $_db->prep_exec($sql, $params);
		return $sertifika;
		//return $_db->prep_exec($sql, $params);
	}
	
	function getBelgeDataByKURTARYET($kurulus, $tarih, $yeterlilik){
		$_db = JFactory::getOracleDBO ();
		$sertifika = array();
		
		$sql = " SELECT DISTINCT SERTIFIKA_BASVURU_ID, SERTIFIKA_DUZENLENME_TARIHI, SERTIFIKA_GECERLILIK_TARIHI,  SINAV_TARIHI, YETKILI, UNVAN, OGRENME_CIKTI,  SERTIFIKA_NO,  M_SINAV_ID, TC_KIMLIK, TO_CHAR(SERTIFIKA_BASVURU_TARIHI, 'dd.mm.yyyy') AS SER_TARIH, USER_ID, KURULUS_ADI, YETERLILIK_ID, YETERLILIK_KODU, YETERLILIK_ADI, SEVIYE_ID, OGRENCI_ADI, OGRENCI_SOYADI, OGRENCI_DOGUM_TARIHI, OGRENCI_DOGUM_YERI, OGRENCI_BABA_ADI, 
				           YETERLILIK_ALT_BIRIM_ADI AS BIRIM_ADI, YETERLILIK_KODU AS BIRIM_KODU, YETERLILIK_ALT_BIRIM_NO AS BIRIM_NO ,  SERTIFIKA_DURUM_ID, SERTIFIKA_DURUM_ADI, REV_YETERLILIK_KODU, REVIZYON_NO, REV_YAYIN_TARIHI, REVIZYON_TARIHI, YENI_MI 
				          FROM M_SERTIFIKA_BASVURU 
				          
									JOIN M_OGRENCI USING(TC_KIMLIK) 
									JOIN M_KURULUS USING(USER_ID) 
									JOIN M_YETERLILIK ON M_SERTIFIKA_BASVURU.YETERLILIK_ID = M_YETERLILIK.YETERLILIK_ID
				          JOIN M_YETERLILIK_ALT_BIRIM ON (M_SERTIFIKA_BASVURU.BIRIM_ID = M_YETERLILIK_ALT_BIRIM.YETERLILIK_ALT_BIRIM_ID AND M_SERTIFIKA_BASVURU.YETERLILIK_ID = M_YETERLILIK_ALT_BIRIM.YETERLILIK_ID)
				          JOIN PM_SERTIFIKA_DURUM USING(SERTIFIKA_DURUM_ID)
				          WHERE YENI_MI = 0 AND USER_ID = ? AND TO_CHAR(SERTIFIKA_BASVURU_TARIHI, 'dd.mm.yyyy') = ? AND YETERLILIK_ID = ? 
				UNION
				 SELECT DISTINCT SERTIFIKA_BASVURU_ID, SERTIFIKA_DUZENLENME_TARIHI, SERTIFIKA_GECERLILIK_TARIHI,  SINAV_TARIHI, YETKILI, UNVAN, OGRENME_CIKTI,  SERTIFIKA_NO,  M_SINAV_ID, TC_KIMLIK, TO_CHAR(SERTIFIKA_BASVURU_TARIHI, 'dd.mm.yyyy') AS SER_TARIH, USER_ID, KURULUS_ADI, YETERLILIK_ID, YETERLILIK_KODU, YETERLILIK_ADI, SEVIYE_ID, OGRENCI_ADI, OGRENCI_SOYADI, OGRENCI_DOGUM_TARIHI, OGRENCI_DOGUM_YERI, OGRENCI_BABA_ADI, 
    		 BIRIM_ADI, BIRIM_KODU, BIRIM_NO,   SERTIFIKA_DURUM_ID, SERTIFIKA_DURUM_ADI, REV_YETERLILIK_KODU, REVIZYON_NO, REV_YAYIN_TARIHI, REVIZYON_TARIHI, YENI_MI 
		    FROM M_SERTIFIKA_BASVURU
					JOIN M_OGRENCI USING(TC_KIMLIK) 
					JOIN M_KURULUS USING(USER_ID) 
					JOIN M_YETERLILIK USING(YETERLILIK_ID)
          JOIN M_BIRIM_OLCME_DEGERLENDIRME ON (M_SERTIFIKA_BASVURU.BIRIM_ID = M_BIRIM_OLCME_DEGERLENDIRME.BIRIM_ID AND M_SERTIFIKA_BASVURU.BIRIM_SINAV_ID = M_BIRIM_OLCME_DEGERLENDIRME.ID)
          			JOIN M_BIRIM ON M_SERTIFIKA_BASVURU.BIRIM_ID = M_BIRIM.BIRIM_ID
                JOIN PM_SERTIFIKA_DURUM USING(SERTIFIKA_DURUM_ID)
				          WHERE YENI_MI = 1 AND USER_ID = ? AND TO_CHAR(SERTIFIKA_BASVURU_TARIHI, 'dd.mm.yyyy') = ? AND YETERLILIK_ID = ? ORDER BY SERTIFIKA_BASVURU_ID, TC_KIMLIK, BIRIM_KODU, BIRIM_NO";
		
		$params = array($kurulus, $tarih, $yeterlilik, $kurulus, $tarih, $yeterlilik);
		$sertifika[0] =  $_db->prep_exec($sql, $params);
		return $sertifika;
		//return $_db->prep_exec($sql, $params);
	}
	
	function getBelgeDataByKURYET($kurulus, $yeterlilik){
		$_db = JFactory::getOracleDBO ();
		$sertifika = array();
		
		$sql = " SELECT DISTINCT SERTIFIKA_BASVURU_ID, SERTIFIKA_DUZENLENME_TARIHI, SERTIFIKA_GECERLILIK_TARIHI,  SINAV_TARIHI, YETKILI, UNVAN, OGRENME_CIKTI,  SERTIFIKA_NO,  M_SINAV_ID, TC_KIMLIK, TO_CHAR(SERTIFIKA_BASVURU_TARIHI, 'dd.mm.yyyy') AS SER_TARIH, USER_ID, KURULUS_ADI, YETERLILIK_ID, YETERLILIK_KODU, YETERLILIK_ADI, SEVIYE_ID, OGRENCI_ADI, OGRENCI_SOYADI, OGRENCI_DOGUM_TARIHI, OGRENCI_DOGUM_YERI, OGRENCI_BABA_ADI, 
				           YETERLILIK_ALT_BIRIM_ADI AS BIRIM_ADI, YETERLILIK_KODU AS BIRIM_KODU, YETERLILIK_ALT_BIRIM_NO AS BIRIM_NO ,  SERTIFIKA_DURUM_ID, SERTIFIKA_DURUM_ADI, REV_YETERLILIK_KODU, REVIZYON_NO, REV_YAYIN_TARIHI, REVIZYON_TARIHI, YENI_MI 
				          FROM M_SERTIFIKA_BASVURU 
				          
									JOIN M_OGRENCI USING(TC_KIMLIK) 
									JOIN M_KURULUS USING(USER_ID) 
									JOIN M_YETERLILIK ON M_SERTIFIKA_BASVURU.YETERLILIK_ID = M_YETERLILIK.YETERLILIK_ID
				          JOIN M_YETERLILIK_ALT_BIRIM ON (M_SERTIFIKA_BASVURU.BIRIM_ID = M_YETERLILIK_ALT_BIRIM.YETERLILIK_ALT_BIRIM_ID AND M_SERTIFIKA_BASVURU.YETERLILIK_ID = M_YETERLILIK_ALT_BIRIM.YETERLILIK_ID)
				          JOIN PM_SERTIFIKA_DURUM USING(SERTIFIKA_DURUM_ID)
				          WHERE YENI_MI = 0 AND USER_ID = ? AND YETERLILIK_ID = ? 
				UNION
				 SELECT DISTINCT SERTIFIKA_BASVURU_ID, SERTIFIKA_DUZENLENME_TARIHI, SERTIFIKA_GECERLILIK_TARIHI,  SINAV_TARIHI, YETKILI, UNVAN, OGRENME_CIKTI,  SERTIFIKA_NO,  M_SINAV_ID, TC_KIMLIK, TO_CHAR(SERTIFIKA_BASVURU_TARIHI, 'dd.mm.yyyy') AS SER_TARIH, USER_ID, KURULUS_ADI, YETERLILIK_ID, YETERLILIK_KODU, YETERLILIK_ADI, SEVIYE_ID, OGRENCI_ADI, OGRENCI_SOYADI, OGRENCI_DOGUM_TARIHI, OGRENCI_DOGUM_YERI, OGRENCI_BABA_ADI, 
    		 BIRIM_ADI, BIRIM_KODU, BIRIM_NO,   SERTIFIKA_DURUM_ID, SERTIFIKA_DURUM_ADI, REV_YETERLILIK_KODU, REVIZYON_NO, REV_YAYIN_TARIHI, REVIZYON_TARIHI, YENI_MI 
		    FROM M_SERTIFIKA_BASVURU
					JOIN M_OGRENCI USING(TC_KIMLIK) 
					JOIN M_KURULUS USING(USER_ID) 
					JOIN M_YETERLILIK USING(YETERLILIK_ID)
          JOIN M_BIRIM_OLCME_DEGERLENDIRME ON (M_SERTIFIKA_BASVURU.BIRIM_ID = M_BIRIM_OLCME_DEGERLENDIRME.BIRIM_ID AND M_SERTIFIKA_BASVURU.BIRIM_SINAV_ID = M_BIRIM_OLCME_DEGERLENDIRME.ID)
          			JOIN M_BIRIM ON M_SERTIFIKA_BASVURU.BIRIM_ID = M_BIRIM.BIRIM_ID
                JOIN PM_SERTIFIKA_DURUM USING(SERTIFIKA_DURUM_ID)
				          WHERE YENI_MI = 1 AND USER_ID = ? AND YETERLILIK_ID = ? ORDER BY SERTIFIKA_BASVURU_ID, TC_KIMLIK, BIRIM_KODU, BIRIM_NO";
		
		$params = array($kurulus, $yeterlilik, $kurulus, $yeterlilik);
		$sertifika[0] =  $_db->prep_exec($sql, $params);
		
		$kursql = "SELECT KURULUS_ADI FROM M_KURULUS WHERE USER_ID = ?";
		$belgekur = $_db->prep_exec($kursql, array($kurulus));
		
		$yetsql = "SELECT YETERLILIK_ADI FROM M_YETERLILIK WHERE YETERLILIK_ID = ?";
		$yetad = $_db->prep_exec($yetsql, array($yeterlilik));
		
		$sql2 = "SELECT * FROM M_BELGE_SORGU WHERE UCASE(YETERLILIK_ADI) = UCASE(?) AND UCASE(BELGELENDIRME_KURULUSU) = UCASE(?)";
		$sertifika[1] = $_db->prep_exec($sql2, array($yetad[0]["YETERLILIK_ADI"], $belgekur[0]["KURULUS_ADI"]));
		
		return $sertifika;
		//return $_db->prep_exec($sql, $params);
	}
	
	function getBelgeDataByKURTAR($kurulus, $tarih){
		$_db = JFactory::getOracleDBO ();
		$sertifika = array();
		
		$sql = " SELECT DISTINCT SERTIFIKA_BASVURU_ID, SERTIFIKA_DUZENLENME_TARIHI, SERTIFIKA_GECERLILIK_TARIHI,  SINAV_TARIHI, YETKILI, UNVAN, OGRENME_CIKTI,  SERTIFIKA_NO,  M_SINAV_ID, TC_KIMLIK, TO_CHAR(SERTIFIKA_BASVURU_TARIHI, 'dd.mm.yyyy') AS SER_TARIH, USER_ID, KURULUS_ADI, YETERLILIK_ID, YETERLILIK_KODU, YETERLILIK_ADI, SEVIYE_ID, OGRENCI_ADI, OGRENCI_SOYADI, OGRENCI_DOGUM_TARIHI, OGRENCI_DOGUM_YERI, OGRENCI_BABA_ADI, 
				           YETERLILIK_ALT_BIRIM_ADI AS BIRIM_ADI, YETERLILIK_KODU AS BIRIM_KODU, YETERLILIK_ALT_BIRIM_NO AS BIRIM_NO ,  SERTIFIKA_DURUM_ID, SERTIFIKA_DURUM_ADI, REV_YETERLILIK_KODU, REVIZYON_NO, REV_YAYIN_TARIHI, REVIZYON_TARIHI, YENI_MI 
				          FROM M_SERTIFIKA_BASVURU 
				          
									JOIN M_OGRENCI USING(TC_KIMLIK) 
									JOIN M_KURULUS USING(USER_ID) 
									JOIN M_YETERLILIK ON M_SERTIFIKA_BASVURU.YETERLILIK_ID = M_YETERLILIK.YETERLILIK_ID
				          JOIN M_YETERLILIK_ALT_BIRIM ON (M_SERTIFIKA_BASVURU.BIRIM_ID = M_YETERLILIK_ALT_BIRIM.YETERLILIK_ALT_BIRIM_ID AND M_SERTIFIKA_BASVURU.YETERLILIK_ID = M_YETERLILIK_ALT_BIRIM.YETERLILIK_ID)
				          JOIN PM_SERTIFIKA_DURUM USING(SERTIFIKA_DURUM_ID)
				          WHERE YENI_MI = 0 AND TO_CHAR(SERTIFIKA_BASVURU_TARIHI, 'dd.mm.yyyy') = ? AND USER_ID = ?  
				UNION
				 SELECT DISTINCT SERTIFIKA_BASVURU_ID, SERTIFIKA_DUZENLENME_TARIHI, SERTIFIKA_GECERLILIK_TARIHI,  SINAV_TARIHI, YETKILI, UNVAN, OGRENME_CIKTI,  SERTIFIKA_NO,  M_SINAV_ID, TC_KIMLIK, TO_CHAR(SERTIFIKA_BASVURU_TARIHI, 'dd.mm.yyyy') AS SER_TARIH, USER_ID, KURULUS_ADI, YETERLILIK_ID, YETERLILIK_KODU, YETERLILIK_ADI, SEVIYE_ID, OGRENCI_ADI, OGRENCI_SOYADI, OGRENCI_DOGUM_TARIHI, OGRENCI_DOGUM_YERI, OGRENCI_BABA_ADI, 
    		 BIRIM_ADI, BIRIM_KODU, BIRIM_NO,   SERTIFIKA_DURUM_ID, SERTIFIKA_DURUM_ADI, REV_YETERLILIK_KODU, REVIZYON_NO, REV_YAYIN_TARIHI, REVIZYON_TARIHI, YENI_MI 
		    FROM M_SERTIFIKA_BASVURU
					JOIN M_OGRENCI USING(TC_KIMLIK) 
					JOIN M_KURULUS USING(USER_ID) 
					JOIN M_YETERLILIK USING(YETERLILIK_ID)
          JOIN M_BIRIM_OLCME_DEGERLENDIRME ON (M_SERTIFIKA_BASVURU.BIRIM_ID = M_BIRIM_OLCME_DEGERLENDIRME.BIRIM_ID AND M_SERTIFIKA_BASVURU.BIRIM_SINAV_ID = M_BIRIM_OLCME_DEGERLENDIRME.ID)
          			JOIN M_BIRIM ON M_SERTIFIKA_BASVURU.BIRIM_ID = M_BIRIM.BIRIM_ID
                JOIN PM_SERTIFIKA_DURUM USING(SERTIFIKA_DURUM_ID)
				          WHERE YENI_MI = 1 AND TO_CHAR(SERTIFIKA_BASVURU_TARIHI, 'dd.mm.yyyy') = ? AND USER_ID = ? ORDER BY SERTIFIKA_BASVURU_ID, TC_KIMLIK, BIRIM_KODU, BIRIM_NO";
		
		$params = array($tarih, $kurulus, $tarih, $kurulus);
		$sertifika[0] =  $_db->prep_exec($sql, $params);
		return $sertifika;
		//return $_db->prep_exec($sql, $params);
	}
	
	function getBelgeDataByKURTC($kurulus, $kimlik_no){
		$_db = JFactory::getOracleDBO ();
		$sertifika = array();
		
		$sql = " SELECT DISTINCT SERTIFIKA_BASVURU_ID, SERTIFIKA_DUZENLENME_TARIHI, SERTIFIKA_GECERLILIK_TARIHI,  SINAV_TARIHI, YETKILI, UNVAN, OGRENME_CIKTI,  SERTIFIKA_NO,  M_SINAV_ID, TC_KIMLIK, TO_CHAR(SERTIFIKA_BASVURU_TARIHI, 'dd.mm.yyyy') AS SER_TARIH, USER_ID, KURULUS_ADI, YETERLILIK_ID, YETERLILIK_KODU, YETERLILIK_ADI, SEVIYE_ID, OGRENCI_ADI, OGRENCI_SOYADI, OGRENCI_DOGUM_TARIHI, OGRENCI_DOGUM_YERI, OGRENCI_BABA_ADI, 
				           YETERLILIK_ALT_BIRIM_ADI AS BIRIM_ADI, YETERLILIK_KODU AS BIRIM_KODU, YETERLILIK_ALT_BIRIM_NO AS BIRIM_NO ,  SERTIFIKA_DURUM_ID, SERTIFIKA_DURUM_ADI, REV_YETERLILIK_KODU, REVIZYON_NO, REV_YAYIN_TARIHI, REVIZYON_TARIHI, YENI_MI 
				          FROM M_SERTIFIKA_BASVURU 
				          
									JOIN M_OGRENCI USING(TC_KIMLIK) 
									JOIN M_KURULUS USING(USER_ID) 
									JOIN M_YETERLILIK ON M_SERTIFIKA_BASVURU.YETERLILIK_ID = M_YETERLILIK.YETERLILIK_ID
				          JOIN M_YETERLILIK_ALT_BIRIM ON (M_SERTIFIKA_BASVURU.BIRIM_ID = M_YETERLILIK_ALT_BIRIM.YETERLILIK_ALT_BIRIM_ID AND M_SERTIFIKA_BASVURU.YETERLILIK_ID = M_YETERLILIK_ALT_BIRIM.YETERLILIK_ID)
				          JOIN PM_SERTIFIKA_DURUM USING(SERTIFIKA_DURUM_ID)
				          WHERE YENI_MI = 0 AND USER_ID = ? AND TC_KIMLIK = ? 
				UNION
				 SELECT DISTINCT SERTIFIKA_BASVURU_ID, SERTIFIKA_DUZENLENME_TARIHI, SERTIFIKA_GECERLILIK_TARIHI,  SINAV_TARIHI, YETKILI, UNVAN, OGRENME_CIKTI,  SERTIFIKA_NO,  M_SINAV_ID, TC_KIMLIK, TO_CHAR(SERTIFIKA_BASVURU_TARIHI, 'dd.mm.yyyy') AS SER_TARIH, USER_ID, KURULUS_ADI, YETERLILIK_ID, YETERLILIK_KODU, YETERLILIK_ADI, SEVIYE_ID, OGRENCI_ADI, OGRENCI_SOYADI, OGRENCI_DOGUM_TARIHI, OGRENCI_DOGUM_YERI, OGRENCI_BABA_ADI, 
    		 BIRIM_ADI, BIRIM_KODU, BIRIM_NO,   SERTIFIKA_DURUM_ID, SERTIFIKA_DURUM_ADI, REV_YETERLILIK_KODU, REVIZYON_NO, REV_YAYIN_TARIHI, REVIZYON_TARIHI, YENI_MI 
		    FROM M_SERTIFIKA_BASVURU
					JOIN M_OGRENCI USING(TC_KIMLIK) 
					JOIN M_KURULUS USING(USER_ID) 
					JOIN M_YETERLILIK USING(YETERLILIK_ID)
          JOIN M_BIRIM_OLCME_DEGERLENDIRME ON (M_SERTIFIKA_BASVURU.BIRIM_ID = M_BIRIM_OLCME_DEGERLENDIRME.BIRIM_ID AND M_SERTIFIKA_BASVURU.BIRIM_SINAV_ID = M_BIRIM_OLCME_DEGERLENDIRME.ID)
          			JOIN M_BIRIM ON M_SERTIFIKA_BASVURU.BIRIM_ID = M_BIRIM.BIRIM_ID
                JOIN PM_SERTIFIKA_DURUM USING(SERTIFIKA_DURUM_ID)
				          WHERE YENI_MI = 1 AND USER_ID = ? AND TC_KIMLIK = ? ORDER BY SERTIFIKA_BASVURU_ID, TC_KIMLIK, BIRIM_KODU, BIRIM_NO";
		
		$params = array($kurulus, $kimlik_no, $kurulus, $kimlik_no);
		$sertifika[0] =  $_db->prep_exec($sql, $params);
		
		$kursql = "SELECT KURULUS_ADI FROM M_KURULUS WHERE USER_ID = ?";
		$belgekur = $_db->prep_exec($kursql, array($kurulus));
		
		$sql2 = "SELECT * FROM M_BELGE_SORGU WHERE TCKIMLIKNO = ? AND UCASE(BELGELENDIRME_KURULUSU) = UCASE(?)";
		$sertifika[1] = $_db->prep_exec($sql2, array($kimlik_no, $belgekur[0]["KURULUS_ADI"]));
		
		return $sertifika;
		//return $_db->prep_exec($sql, $params);
	}
	
	function getBelgeDataByYETTAR($yeterlilik, $tarih){
		$_db = JFactory::getOracleDBO ();
		$sertifika = array();
		
		$sql = " SELECT DISTINCT SERTIFIKA_BASVURU_ID, SERTIFIKA_DUZENLENME_TARIHI, SERTIFIKA_GECERLILIK_TARIHI,  SINAV_TARIHI, YETKILI, UNVAN, OGRENME_CIKTI,  SERTIFIKA_NO,  M_SINAV_ID, TC_KIMLIK, TO_CHAR(SERTIFIKA_BASVURU_TARIHI, 'dd.mm.yyyy') AS SER_TARIH, USER_ID, KURULUS_ADI, YETERLILIK_ID, YETERLILIK_KODU, YETERLILIK_ADI, SEVIYE_ID, OGRENCI_ADI, OGRENCI_SOYADI, OGRENCI_DOGUM_TARIHI, OGRENCI_DOGUM_YERI, OGRENCI_BABA_ADI, 
				           YETERLILIK_ALT_BIRIM_ADI AS BIRIM_ADI, YETERLILIK_KODU AS BIRIM_KODU, YETERLILIK_ALT_BIRIM_NO AS BIRIM_NO ,  SERTIFIKA_DURUM_ID, SERTIFIKA_DURUM_ADI, REV_YETERLILIK_KODU, REVIZYON_NO, REV_YAYIN_TARIHI, REVIZYON_TARIHI, YENI_MI 
				          FROM M_SERTIFIKA_BASVURU 
				          
									JOIN M_OGRENCI USING(TC_KIMLIK) 
									JOIN M_KURULUS USING(USER_ID) 
									JOIN M_YETERLILIK ON M_SERTIFIKA_BASVURU.YETERLILIK_ID = M_YETERLILIK.YETERLILIK_ID
				          JOIN M_YETERLILIK_ALT_BIRIM ON (M_SERTIFIKA_BASVURU.BIRIM_ID = M_YETERLILIK_ALT_BIRIM.YETERLILIK_ALT_BIRIM_ID AND M_SERTIFIKA_BASVURU.YETERLILIK_ID = M_YETERLILIK_ALT_BIRIM.YETERLILIK_ID)
				          JOIN PM_SERTIFIKA_DURUM USING(SERTIFIKA_DURUM_ID)
				          WHERE YENI_MI = 0 AND TO_CHAR(SERTIFIKA_BASVURU_TARIHI, 'dd.mm.yyyy') = ? AND YETERLILIK_ID = ? 
				UNION
				 SELECT DISTINCT SERTIFIKA_BASVURU_ID, SERTIFIKA_DUZENLENME_TARIHI, SERTIFIKA_GECERLILIK_TARIHI,  SINAV_TARIHI, YETKILI, UNVAN, OGRENME_CIKTI,  SERTIFIKA_NO,  M_SINAV_ID, TC_KIMLIK, TO_CHAR(SERTIFIKA_BASVURU_TARIHI, 'dd.mm.yyyy') AS SER_TARIH, USER_ID, KURULUS_ADI, YETERLILIK_ID, YETERLILIK_KODU, YETERLILIK_ADI, SEVIYE_ID, OGRENCI_ADI, OGRENCI_SOYADI, OGRENCI_DOGUM_TARIHI, OGRENCI_DOGUM_YERI, OGRENCI_BABA_ADI, 
    		 BIRIM_ADI, BIRIM_KODU, BIRIM_NO,   SERTIFIKA_DURUM_ID, SERTIFIKA_DURUM_ADI, REV_YETERLILIK_KODU, REVIZYON_NO, REV_YAYIN_TARIHI, REVIZYON_TARIHI, YENI_MI 
		    FROM M_SERTIFIKA_BASVURU
					JOIN M_OGRENCI USING(TC_KIMLIK) 
					JOIN M_KURULUS USING(USER_ID) 
					JOIN M_YETERLILIK USING(YETERLILIK_ID)
          JOIN M_BIRIM_OLCME_DEGERLENDIRME ON (M_SERTIFIKA_BASVURU.BIRIM_ID = M_BIRIM_OLCME_DEGERLENDIRME.BIRIM_ID AND M_SERTIFIKA_BASVURU.BIRIM_SINAV_ID = M_BIRIM_OLCME_DEGERLENDIRME.ID)
          			JOIN M_BIRIM ON M_SERTIFIKA_BASVURU.BIRIM_ID = M_BIRIM.BIRIM_ID
                JOIN PM_SERTIFIKA_DURUM USING(SERTIFIKA_DURUM_ID)
				          WHERE YENI_MI = 1 AND TO_CHAR(SERTIFIKA_BASVURU_TARIHI, 'dd.mm.yyyy') = ? AND YETERLILIK_ID = ? ORDER BY SERTIFIKA_BASVURU_ID, TC_KIMLIK, BIRIM_KODU, BIRIM_NO";
		
		$params = array($tarih, $yeterlilik, $tarih, $yeterlilik);
		$sertifika[0] =  $_db->prep_exec($sql, $params);
		return $sertifika;
		//return $_db->prep_exec($sql, $params);
	}
	
	function getBelgeDataByYETTC($yeterlilik, $kimlik_no){
		$_db = JFactory::getOracleDBO ();
		$sertifika = array();
		
		$sql = "  SELECT DISTINCT SERTIFIKA_BASVURU_ID, SERTIFIKA_DUZENLENME_TARIHI, SERTIFIKA_GECERLILIK_TARIHI,  SINAV_TARIHI, YETKILI, UNVAN, OGRENME_CIKTI,  SERTIFIKA_NO,  M_SINAV_ID, TC_KIMLIK, TO_CHAR(SERTIFIKA_BASVURU_TARIHI, 'dd.mm.yyyy') AS SER_TARIH, USER_ID, KURULUS_ADI, YETERLILIK_ID, YETERLILIK_KODU, YETERLILIK_ADI, SEVIYE_ID, OGRENCI_ADI, OGRENCI_SOYADI, OGRENCI_DOGUM_TARIHI, OGRENCI_DOGUM_YERI, OGRENCI_BABA_ADI, 
				           YETERLILIK_ALT_BIRIM_ADI AS BIRIM_ADI, YETERLILIK_KODU AS BIRIM_KODU, YETERLILIK_ALT_BIRIM_NO AS BIRIM_NO ,  SERTIFIKA_DURUM_ID, SERTIFIKA_DURUM_ADI, REV_YETERLILIK_KODU, REVIZYON_NO, REV_YAYIN_TARIHI, REVIZYON_TARIHI, YENI_MI 
				          FROM M_SERTIFIKA_BASVURU 
				          
									JOIN M_OGRENCI USING(TC_KIMLIK) 
									JOIN M_KURULUS USING(USER_ID) 
									JOIN M_YETERLILIK ON M_SERTIFIKA_BASVURU.YETERLILIK_ID = M_YETERLILIK.YETERLILIK_ID
				          JOIN M_YETERLILIK_ALT_BIRIM ON (M_SERTIFIKA_BASVURU.BIRIM_ID = M_YETERLILIK_ALT_BIRIM.YETERLILIK_ALT_BIRIM_ID AND M_SERTIFIKA_BASVURU.YETERLILIK_ID = M_YETERLILIK_ALT_BIRIM.YETERLILIK_ID)
				          JOIN PM_SERTIFIKA_DURUM USING(SERTIFIKA_DURUM_ID)
				          WHERE YENI_MI = 0 AND YETERLILIK_ID = ? AND TC_KIMLIK = ? 
				UNION
				 SELECT DISTINCT SERTIFIKA_BASVURU_ID, SERTIFIKA_DUZENLENME_TARIHI, SERTIFIKA_GECERLILIK_TARIHI,  SINAV_TARIHI, YETKILI, UNVAN, OGRENME_CIKTI,  SERTIFIKA_NO,  M_SINAV_ID, TC_KIMLIK, TO_CHAR(SERTIFIKA_BASVURU_TARIHI, 'dd.mm.yyyy') AS SER_TARIH, USER_ID, KURULUS_ADI, YETERLILIK_ID, YETERLILIK_KODU, YETERLILIK_ADI, SEVIYE_ID, OGRENCI_ADI, OGRENCI_SOYADI, OGRENCI_DOGUM_TARIHI, OGRENCI_DOGUM_YERI, OGRENCI_BABA_ADI, 
    		 BIRIM_ADI, BIRIM_KODU, BIRIM_NO,   SERTIFIKA_DURUM_ID, SERTIFIKA_DURUM_ADI, REV_YETERLILIK_KODU, REVIZYON_NO, REV_YAYIN_TARIHI, REVIZYON_TARIHI, YENI_MI 
		    FROM M_SERTIFIKA_BASVURU
					JOIN M_OGRENCI USING(TC_KIMLIK) 
					JOIN M_KURULUS USING(USER_ID) 
					JOIN M_YETERLILIK USING(YETERLILIK_ID)
          JOIN M_BIRIM_OLCME_DEGERLENDIRME ON (M_SERTIFIKA_BASVURU.BIRIM_ID = M_BIRIM_OLCME_DEGERLENDIRME.BIRIM_ID AND M_SERTIFIKA_BASVURU.BIRIM_SINAV_ID = M_BIRIM_OLCME_DEGERLENDIRME.ID)
          			JOIN M_BIRIM ON M_SERTIFIKA_BASVURU.BIRIM_ID = M_BIRIM.BIRIM_ID
                JOIN PM_SERTIFIKA_DURUM USING(SERTIFIKA_DURUM_ID)
				          WHERE YENI_MI = 1 AND YETERLILIK_ID = ? AND TC_KIMLIK = ? ORDER BY SERTIFIKA_BASVURU_ID, TC_KIMLIK, BIRIM_KODU, BIRIM_NO";
		
		$params = array($yeterlilik, $kimlik_no, $yeterlilik, $kimlik_no);
		$sertifika[0] =  $_db->prep_exec($sql, $params);
		
		$yetsql = "SELECT YETERLILIK_ADI FROM M_YETERLILIK WHERE YETERLILIK_ID = ?";
		$yetad = $_db->prep_exec($yetsql, array($yeterlilik));
		
		$sql2 = "SELECT * FROM M_BELGE_SORGU WHERE TCKIMLIKNO = ? AND UCASE(YETERLILIK_ADI) = UCASE(?)";
		$sertifika[1] = $_db->prep_exec($sql2, array($kimlik_no, $yetad[0]["YETERLILIK_ADI"]));		
		
		return $sertifika;
		//return $_db->prep_exec($sql, $params);
	}
	
	function getBelgeDataByTARTC($tarih, $kimlik_no){
		$_db = JFactory::getOracleDBO ();
		$sertifika = array();
		
		$sql = "  SELECT DISTINCT SERTIFIKA_BASVURU_ID, SERTIFIKA_DUZENLENME_TARIHI, SERTIFIKA_GECERLILIK_TARIHI,  SINAV_TARIHI, YETKILI, UNVAN, OGRENME_CIKTI,  SERTIFIKA_NO,  M_SINAV_ID, TC_KIMLIK, TO_CHAR(SERTIFIKA_BASVURU_TARIHI, 'dd.mm.yyyy') AS SER_TARIH, USER_ID, KURULUS_ADI, YETERLILIK_ID, YETERLILIK_KODU, YETERLILIK_ADI, SEVIYE_ID, OGRENCI_ADI, OGRENCI_SOYADI, OGRENCI_DOGUM_TARIHI, OGRENCI_DOGUM_YERI, OGRENCI_BABA_ADI, 
				           YETERLILIK_ALT_BIRIM_ADI AS BIRIM_ADI, YETERLILIK_KODU AS BIRIM_KODU, YETERLILIK_ALT_BIRIM_NO AS BIRIM_NO ,  SERTIFIKA_DURUM_ID, SERTIFIKA_DURUM_ADI, REV_YETERLILIK_KODU, REVIZYON_NO, REV_YAYIN_TARIHI, REVIZYON_TARIHI, YENI_MI 
				          FROM M_SERTIFIKA_BASVURU 
									JOIN M_OGRENCI USING(TC_KIMLIK) 
									JOIN M_KURULUS USING(USER_ID) 
									JOIN M_YETERLILIK ON M_SERTIFIKA_BASVURU.YETERLILIK_ID = M_YETERLILIK.YETERLILIK_ID
				          JOIN M_YETERLILIK_ALT_BIRIM ON (M_SERTIFIKA_BASVURU.BIRIM_ID = M_YETERLILIK_ALT_BIRIM.YETERLILIK_ALT_BIRIM_ID AND M_SERTIFIKA_BASVURU.YETERLILIK_ID = M_YETERLILIK_ALT_BIRIM.YETERLILIK_ID)
				          JOIN PM_SERTIFIKA_DURUM USING(SERTIFIKA_DURUM_ID)
				          WHERE YENI_MI = 0 AND TO_CHAR(SERTIFIKA_BASVURU_TARIHI, 'dd.mm.yyyy') = ? AND TC_KIMLIK = ? 
				UNION
				 SELECT DISTINCT SERTIFIKA_BASVURU_ID, SERTIFIKA_DUZENLENME_TARIHI, SERTIFIKA_GECERLILIK_TARIHI,  SINAV_TARIHI, YETKILI, UNVAN, OGRENME_CIKTI,  SERTIFIKA_NO,  M_SINAV_ID, TC_KIMLIK, TO_CHAR(SERTIFIKA_BASVURU_TARIHI, 'dd.mm.yyyy') AS SER_TARIH, USER_ID, KURULUS_ADI, YETERLILIK_ID, YETERLILIK_KODU, YETERLILIK_ADI, SEVIYE_ID, OGRENCI_ADI, OGRENCI_SOYADI, OGRENCI_DOGUM_TARIHI, OGRENCI_DOGUM_YERI, OGRENCI_BABA_ADI, 
    		 BIRIM_ADI, BIRIM_KODU, BIRIM_NO,   SERTIFIKA_DURUM_ID, SERTIFIKA_DURUM_ADI, REV_YETERLILIK_KODU, REVIZYON_NO, REV_YAYIN_TARIHI, REVIZYON_TARIHI, YENI_MI 
		    FROM M_SERTIFIKA_BASVURU
					JOIN M_OGRENCI USING(TC_KIMLIK) 
					JOIN M_KURULUS USING(USER_ID) 
					JOIN M_YETERLILIK USING(YETERLILIK_ID)
          JOIN M_BIRIM_OLCME_DEGERLENDIRME ON (M_SERTIFIKA_BASVURU.BIRIM_ID = M_BIRIM_OLCME_DEGERLENDIRME.BIRIM_ID AND M_SERTIFIKA_BASVURU.BIRIM_SINAV_ID = M_BIRIM_OLCME_DEGERLENDIRME.ID)
          			JOIN M_BIRIM ON M_SERTIFIKA_BASVURU.BIRIM_ID = M_BIRIM.BIRIM_ID
                JOIN PM_SERTIFIKA_DURUM USING(SERTIFIKA_DURUM_ID)
				          WHERE YENI_MI = 1 AND TO_CHAR(SERTIFIKA_BASVURU_TARIHI, 'dd.mm.yyyy') = ? AND TC_KIMLIK = ? ORDER BY SERTIFIKA_BASVURU_ID, TC_KIMLIK, BIRIM_KODU, BIRIM_NO";
		
		$params = array($tarih, $kimlik_no, $tarih, $kimlik_no);
		$sertifika[0] =  $_db->prep_exec($sql, $params);
		return $sertifika;
		//return $_db->prep_exec($sql, $params);
	}
	
	function getKurulus(){
		$_db = JFactory::getOracleDBO ();
	
		$sql = "SELECT DISTINCT USER_ID, KURULUS_ADI 
					FROM M_KURULUS JOIN M_BASVURU USING(USER_ID) 
					WHERE BASVURU_TIP_ID = 3 AND BASVURU_DURUM_ID = 6 AND KURULUS_ADI NOT LIKE '%KURUM TEST%' ORDER BY KURULUS_ADI";
	
		return $_db->prep_exec($sql, array());
	}
	
	function getYeterlilik(){
		$db  = &JFactory::getOracleDBO();
		$sql = "SELECT YETERLILIK_ID, YETERLILIK_KODU, YETERLILIK_ADI
						FROM M_YETERLILIK 
						WHERE YETERLILIK_DURUM_ID = 2 AND YETERLILIK_SUREC_DURUM_ID = 1 ORDER BY YETERLILIK_ADI";
		$yeterlilikler = $db->prep_exec($sql,array());
		return $yeterlilikler;
	}
	
	function sertifikaOnayla(){
		$db  = &JFactory::getOracleDBO();
		$sertifika_id = $_POST["serId"];
		$yetkili = $_POST["yetkili"];
		$unvan = $_POST["unvan"];
		$belgegectarih = $_POST["belgegectarih"];
		$belgeduztarih = $_POST["belgeduztarih"];
		$sinavtarih = $_POST["sinavtarih"];
		$belgeno = $_POST["belgeno"];
		$durum = $_POST["durum"];
		$ogrcik = $_POST["ogrenmecikti"];
		
		$serUpdate = "UPDATE M_SERTIFIKA_BASVURU 
			SET SERTIFIKA_DURUM_ID = ?, SERTIFIKA_DUZENLENME_TARIHI = ?, 
			SERTIFIKA_GECERLILIK_TARIHI = ?, SERTIFIKA_NO = ?, YETKILI = ?, UNVAN = ?, 
			SINAV_TARIHI = ?, OGRENME_CIKTI = ?, KURUM_KISI = ?, KURUM_UNVAN = ?, REVIZYON_NO = ?, 
			REV_YETERLILIK_KODU = ?,  REV_YAYIN_TARIHI = ?, REVIZYON_TARIHI = ?
		 	WHERE SERTIFIKA_BASVURU_ID =?";
		$serReddet = "UPDATE M_SERTIFIKA_BASVURU 
			SET SERTIFIKA_DURUM_ID = ? 
		 	WHERE SERTIFIKA_BASVURU_ID =?";
		$serBeklet = "UPDATE M_SERTIFIKA_BASVURU 
			SET SERTIFIKA_DURUM_ID = ? 
		 	WHERE SERTIFIKA_BASVURU_ID =?";
		$sinavsonucuUpdate = "UPDATE M_SINAV_SONUCU SET SERTIFIKA_DURUM_ID = 0 WHERE SERTIFIKA_BASVURU_ID =?";
		$sqlkurum = "SELECT KURUM_KISI, KURUM_UNVAN FROM M_SERTIFIKA_KURUM_YETKILI";
		$kurumyetkili = $db->prep_exec($sqlkurum, array());

		foreach($sertifika_id as $cows){
			if(!empty($belgegectarih[$cows]) && !empty($belgeduztarih[$cows]) && !empty($belgeno[$cows]) && !empty($yetkili[$cows]) && $durum[$cows] == 1){
				$sqlyet = "SELECT DISTINCT YETERLILIK_ID FROM M_SERTIFIKA_BASVURU WHERE SERTIFIKA_BASVURU_ID = ?";
				$yetIds = $db->prep_exec($sqlyet, array($cows));
				$yetId = $yetIds[0]["YETERLILIK_ID"];
				//revizyon
				$rev_yet = $this->getRevizyonBilgi($yetId,$revizyon_no="");
					
				$params = array($durum[$cows],
								$belgeduztarih[$cows], 
								$belgegectarih[$cows], 
								$belgeno[$cows], 
								$yetkili[$cows], 
								$unvan[$cows], 
								$sinavtarih[$cows], 
								$ogrcik[$cows], 
								$kurumyetkili[0]["KURUM_KISI"], 
								$kurumyetkili[0]["KURUM_UNVAN"],
								$rev_yet["REVIZYON_NO"],
								$rev_yet["YETERLILIK_KODU"],
								$rev_yet["YAYIN_TARIHI"],
								$rev_yet["REVIZYON_TARIHI"],
								$cows);
				$db->prep_exec_insert($serUpdate, $params);
				//$db->prep_exec_insert($sertifikaOnay, array($cows, $belgeduztarih[$cows], $belgegectarih[$cows], $belgeno[$cows]));
			}
			else if($durum[$cows] == -1){
				$db->prep_exec_insert($serReddet, array($durum[$cows], $cows));
				$db->prep_exec_insert($sinavsonucuUpdate, array($cows));
				//$db->prep_exec_insert($serifikaSil, array($cows));
			}
			else if($durum[$cows] == 0){
				$db->prep_exec_insert($serBeklet, array($durum[$cows], $cows));
				//$db->prep_exec_insert($serifikaSil, array($cows));
			}
		}
	}
	
	function getLogo($serid){
		$db = JFactory::getOracleDBO();
		
		$sql = "SELECT USER_ID FROM M_SERTIFIKA_BASVURU WHERE SERTIFIKA_BASVURU_ID =?";
		$user_id = $db->prep_exec($sql, array($serid));
		
		$sqlLogo = "SELECT LOGO FROM M_KURULUS WHERE USER_ID = ?";
		$logo = $db->prep_exec($sqlLogo, array($user_id[0]["USER_ID"]));
		
		return $logo[0]["LOGO"];
	}
	
	//revizyon
	function getRevizyonBilgi ($yetId,$revizyon_no){
		$db = JFactory::getOracleDBO();
		if ($revizyon_no==""){
			$revizyon_no= $this->revizyonVarMi($yetId);
		}
		if ($revizyon_no=="00"){
			$sql= "SELECT
												  REVIZYON_NO,
												  YETERLILIK_KODU,
												  TO_CHAR (YAYIN_TARIHI	  , 'dd.mm.yyyy') YAYIN_TARIHI,
												  TO_CHAR (REVIZYON_TARIHI, 'dd.mm.yyyy') REVIZYON_TARIHI,
												  KARAR_SAYI
										   FROM m_yeterlilik 
										   	  JOIN m_taslak_yeterlilik USING (yeterlilik_id) 
										   WHERE yeterlilik_id = ?";
			$params = array ($yetId);
		} else {
			$sql= "SELECT
										REVIZYON_NO, 
										YETERLILIK_KODU,
										TO_CHAR (YAYIN_TARIHI	  , 'dd.mm.yyyy') YAYIN_TARIHI,
										TO_CHAR (REVIZYON_TARIHI, 'dd.mm.yyyy') REVIZYON_TARIHI,
										FROM m_yeterlilik_revizyon
										WHERE yeterlilik_id = ? and REVIZYON_NO= ? ";
	
			$params = array ($yetId,$revizyon_no);
		}
	
		$data = $db->prep_exec($sql, $params);
	
		if (!empty($data))
		return $data[0];
		else
		return null;
	}
	
	function revizyonVarMi($yetId){
		$db = JFactory::getOracleDBO();
		$sql="SELECT * FROM M_YETERLILIK_REVIZYON WHERE yeterlilik_id=? order by revizyon_no desc";
		$sonuc = $db->prep_exec($sql, array($yetId));
		if ($sonuc){
			return $sonuc[0][REVIZYON_NO];
		} else {
			return "00";
		}
	}
	//revizyon
}
?>